### ISSUE TITLE
Bulletin Board Text

### ISSUE THREAD

**Issue by RonaldRob** [crobinson42/therms-public#1]
The main bulletin body panel cuts words at the end of the line. Minor, but if possible would make for easier read if the text was fit to window and not half of a word on one line and the other half on the next.

**Comment by crobinson42** [comment]
fix pull request: https://github.com/crobinson42/therms/pull/68 
fix issue #1, fix navbar-brand on public homepage for phone screens #68

**Comment by crobinson42** [comment]
@jackschappell please verify in sandbox and prod that this is fixed and close the issue.

**Comment by jackschappell** [comment]
@crobinson42 it looks like another bug popped up with the fix.
![bulletinbugtest1](https://cloud.githubusercontent.com/assets/17881452/13888718/2590c65e-ed00-11e5-9715-ae45385c49d7.PNG)

**Comment by crobinson42** [comment]
@jackschappell I JUST now redeployed to prod (therms.io), please check again. Be sure to clear cache when loading.

**Comment by jackschappell** [comment]
Looks to be fixed on the production server!
