### ISSUE TITLE
Margins off when report entry box text area is actively selected

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#113]
When actively typing into a report entry box of any type, the report entry text area receives a dashed border using the following code:
`.form-control:focus {
border: 2px dashed #427cab;
outline: 0;`

When the report entry box is visible for editing, but not actively selected, the dashed border disappears, however the report entry box does not account for this by adding a 2px padding around the text. This causes the text to jump and move when the report entry box is later actively selected by a user in preparation to type in text, or edit existing text.

The simple fix would be to add a 2px padding around the text area that goes away when the user clicks in the report entry box. The dashed border, (at its current width of 2px), would then take its place when the report entry box is actively selected, preventing the text from moving around.

To recreate the issue, fill in any report entry box with a large amount of text until an up/down scrollbar appears. Click somewhere outside of the report entry box and watch the text shift. Click in the report entry box again, and it will move a second time when the dashed border appears. It will continue to do so every time you click inside and outside of the report entry box because of the changed spacing. This affects all web browser platforms, as it is a CSS design bug.

**Comment by crobinson42** [comment]
@jackschappell deployed a fix to sandbox - test it out and advise.

**Comment by jackschappell** [comment]
Roger.

Testing complete. Seems to be working beautifully!
