### ISSUE TITLE
Transfer Protocol Not Secure

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#128]
## This is an in-app submitted User Bug Report

User: Farnsworth, Justin 571d35655debfd5417934bb3
Email: justin.farnsworth@legionsecurity.us
Organization: Legion Security 56e647840ade92b36bf167a8
### User Browser/Device:

UserAgent: Mozilla/5.0 (Linux; Android 7.0; LGMP450 Build/NRD90U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.106 Mobile Safari/537.36
### Issue Described: 

Can't log into the website
### Steps to Reproduce: 

Try to log in

**Comment by jackschappell** [comment]
As per Google Chrome: 

"NET::ERR_CERT_DATE_INVALID
Subject: app.therms.io
Issuer: Let's Encrypt Authority X3
Expires on: Apr 21, 2018
Current date: Apr 21, 2018"

This is also preventing some bug reports from being submitted via THERMS directly.
