### ISSUE TITLE
[Feature] Parking Violation Report

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#13]
Wireframe sketch:
https://www.dropbox.com/s/m8qksh1cbxpd65p/Screenshot%202016-03-24%2021.41.25.png?dl=0

@jackschappell @billpreston please contribute input and notes. You're added as editors on the moqup.com link.

**Comment by jackschappell** [comment]
Perfect!

___

As little as it was used, the VIN section coming back may still come in handy for cases where the vehicle has no license plates. As a recommendation for the state drop-down too, (although it isn't so much related to the visual design directly), it may be worth having options for "None" in the case of no plates, and "Other" for non-U.S. or Government plates. None could essentially show the hidden VIN section, forcing officers to keep from adding a blank entry. With Other, you could show a hidden text field that allows them to fill out the type, or add another dropdown for additional types of plates, such as U.S. Government, CA Exempt, various country names, Diplomat, etc.

(If you really wanted to get technical on the latter idea, you could even have countries that have specific plate systems add another hidden dropdown for the specific location within that country where it has local plate designs).

For some reference: https://en.wikipedia.org/wiki/Vehicle_registration_plate

**Comment by crobinson42** [comment]
@jackschappell This feature is in SBX, please test and close.

**Comment by jackschappell** [comment]
All working and tested!
