### ISSUE TITLE
[FIREFOX] - Location > "+ service" (add service) doesn't work

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#15]
This bug is only in Firefox.

**Comment by crobinson42** [comment]
@jackschappell This was an odd bug found by Mike Sahlbach of TRA Security. Apparently Firefox is it's own animal. I test all the code in Chrome - I'd appreciate it if you were able to start testing the app and it's functionality in Firefox to determine if we have more issues that need to be addressed.

**Comment by jackschappell** [comment]
Roger. I'll try to find some time soon to sweep through in IE, Edge, and Opera too. I'm sure we'll probably find more. Those browsers tend to handle certain things differently sometimes.

**Comment by crobinson42** [comment]
Fixed - https://github.com/crobinson42/therms/pull/92
