### ISSUE TITLE
Unsupported web browser error messages are inconsistent

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#19]
I noticed that the unsupported web browser message for Internet Explorer is completely different from that of any other web browser that is also unsupported. Is this intentional?

For consistency, (and ease of coding in the future), it may be worth merging the two error messages into one. I'm not sure how you have it coded, but it may save space and memory to have it check for Internet Explorer alongside the list of other missing features it tries to detect before marking a web browser as unsupported.

![therms-ie](https://cloud.githubusercontent.com/assets/17881452/14331804/b60b7e22-fbfb-11e5-96e7-07a94ad69f46.PNG)
![therms-safari_windows](https://cloud.githubusercontent.com/assets/17881452/14331808/b8e4b4e2-fbfb-11e5-9461-5272ccea4e06.PNG)

**Comment by crobinson42** [comment]
You are experiencing the intended behavior. Do you suggest forwarding all incompatible browsers to a different page or simply showing the warning message when the browser is incompatible?

I think the resentment towards IE browser steered the intentional redirect to a page saying the browser is incompatible, haha.

![death to ie](https://cloud.githubusercontent.com/assets/5973579/14336944/f3426ee6-fc1d-11e5-9640-6e5c5b10c842.jpg)

**Comment by jackschappell** [comment]
(Down with IE!!!)

![browsers](https://cloud.githubusercontent.com/assets/17881452/14501806/19504b82-015d-11e6-9936-ce3ce8342ad8.png)

Either should work just fine, depending on the amount of work you want to put into it. For testing purposes of new browsers, however, a warning page would allow users to bypass the warning in the event that they know their browser works, but that can also lead to some unintelligent people complaining about THERMS not running properly for them too. If you did go this route, I would recommend a very bold, attention-grabbing disclaimer that it is for them to use at their own risk.

**Comment by crobinson42** [comment]
Allowing user's to login with non-supported browsers (ie: IE) could cause bugs that may ripple effect, unknowns. It's safer IMO to stick with the browsers that support the most recent Ecmascript standards.

**Comment by jackschappell** [comment]
That makes sense. My main concern with this particular issue, though, was that the screens the user is taken to were different depending on the browser. If you block non-supported browsers completely, it would probably be best to redirect them to the same page as the IE block so they still can't log in.
