### ISSUE TITLE
Bulletin Board Comment Section

### ISSUE THREAD

**Issue by RonaldRob** [crobinson42/therms-public#2]
Comment section is only 250 character max or so? It be nice to leave a raving comment when necessary.

**Comment by crobinson42** [comment]
@RonaldRob A single page text message is 250 chars... how many chars do you think is appropriate? You can test the content here: [(http://charcount.com/)]

**Comment by RonaldRob** [comment]
500 characters would be good, at least get 2 small paragraphs in that way.

**Comment by crobinson42** [comment]
Ok, we'll go with 1000 characters for a Bulletin Comment.

Planned this in a feature release next week.
