### ISSUE TITLE
Opera is unsupported?

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#20]
Is the Opera web browser supposed to be unsupported? It passes all of the visible "Dev Info" checks, but is still warned as being outdated or unsupported in the desktop and mobile versions.

Unlike Apple Safari for Windows, (which is discontinued), the login section is still visible despite the error message.

**Comment by crobinson42** [comment]
Opera browser is not specifically *support*. Here's the logic, it's basically warning anyone who doesn't have 1 of the 3 browsers.

```
// DISABLE login if user browser is Internet Explorer (IE)
// & warn about compatibility if user is not chrome,firefox,or safari
		var isCompatibleBrowser = /(chrome|firefox|safari)/gi.test(browserName);
		var isIE = /(ie)/gi.test(browserName);
```

If you're up for testing more browsers we can discuss it. I chose the path of least resistance in the sense that I would rather spend my time coding features and enhancements rather testing more browsers. Those 3 browsers seem to follow the standards [javascript engine] the closest. We use the cutting edge javascript standards [es2015 aka ES6] in our code base. A simple way to know if a browser is up to date is by checking if javascript `Promise` function is available. [(http://caniuse.com/#search=promise)]

Our browser stats in google analytics are showing 53% Chrome already, which puts a smile on my face!
https://www.dropbox.com/s/b8gbfuqgj9r2jz3/Screenshot%202016-04-06%2019.58.28.png?dl=0

**Comment by jackschappell** [comment]
It appears that standard Opera does support that function, but Opera Mini does not. The page doesn't say anything about the standard mobile version of Opera, so I'm assuming that one is okay. (For some dumb reason there are two mobile versions of Opera for Android. The standard one, and the "Mini" version).

Upon testing the Opera Mini version for Android, I noticed that the main menu on the homepage doesn't even work properly, so testing it further would be pointless. That one is definitely worth blocking. It is meant as a lightweight browser for low-end mobile devices anyway, so anyone trying to connect to THERMS with that will probably be having issues loading the page regardless. Most mobile devices these days shouldn't be that low-end, so the effect on users would be minimal.

If you want, I can keep testing the standard version of Opera for Android and Windows, and see how that turns out. So far it appears to be functioning normally. I haven't had a chance to look into it very in-depth yet, though.

**Comment by crobinson42** [comment]
We can add Opera to the list of supported browsers.

- [ ] Add Opera to the list of supported Browsers

**Comment by jackschappell** [comment]
Roger. I'll keep testing things out on it then.

**Comment by crobinson42** [comment]
pulling opera 'official support' as they recently sold to a Chinese company.
