### ISSUE TITLE
Slack on mobile Firefox pop-up renders at top of page 

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#21]
The pop-up for joining slack.io on the homepage renders at the top of the page. Need to check container positioning ie relative.

**Comment by crobinson42** [comment]
https://github.com/rauchg/slackin/issues/182#

**Comment by jackschappell** [comment]
I can't reproduce this in the mobile or Windows versions of Mozilla Firefox. Do you have a screenshot?

**Comment by crobinson42** [comment]
Working in OSX Chrome: http://g.recordit.co/0zSafFznvm.gif

Not Working in OSX Firefox (v45.0.2): http://recordit.co/beDRvESpMK/gif/notify

**Comment by jackschappell** [comment]
Forget my previous reply. I didn't realize you meant the actual popup and not the button. It is definitely broken in Mozilla Firefox for Windows and Android.
