### ISSUE TITLE
Mobile phone locking screen misses information updates

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#23]
> When a mobile user closes their phone screen or it times out - are they getting socket messages from the server? Probably not.. investigate.

The browser, when logged in, stays connected to the backend via sockets. When the user locks their phone screen or goes to a different app, is the socket still connected? This can be tested by simply creating a user, logging in on a mobile device then creating another user and logging in on a desktop and watching the `online` user list to see if the mobile user's name disappears during these actions.

I have tested on iPhone 6 Safari & Chrome, Nexus 5X Android Chrome and they work. 

@jackschappell 
I don't have access to many other phones so if you can test this on as many devices as possible that would be great. Please post comments on your findings.

**Comment by jackschappell** [comment]
This is working perfectly on a Samsung Galaxy S6 running Android 5.1.1 with Google Chrome.

It somewhat works with my iPad on iOS 9.2.1 with Google Chrome, however after approximately one to two minutes the connection is killed by iOS.

Google Chrome is the latest version available in both cases. I'm in the process of updating my iPad to iOS 9.3.1 at the time of writing this, but I don't know if that will make much of a difference.

**Comment by crobinson42** [comment]
Interesting about the iPad killing the connection after 1-2 minutes. That must be a system level ‘sleep’ on all connections to limit bandwidth. When you reopen the browser does it reload the page on it’s own and reconnect or must you do this manually? I’m curious because if this is the case then I need to implement some logic that tests if the socket connection was lost and reload the page to get the most up to date database queries since the connection was lost.

**Comment by jackschappell** [comment]
When I reopen the browser, it refreshes the page automatically, which shows me back as online.

**Comment by crobinson42** [comment]
If the page refreshes automatically when you reopen, then that is GOOD and expected behavior. If it does NOT refresh and does NOT have update information that may have changed while the screen was out of focus on the page, that is BAD...that's what we're monitoring for.

**Comment by jackschappell** [comment]
As of iOS 9.3.1, it looks like it is just refreshing the information on the page instantly when it comes back into focus. I had it out of view for about 3-5 minutes before it refreshed the information. I'm guessing we're covered regardless of whether the user's OS is updated or not, which is awesome.

**Comment by crobinson42** [comment]
@jackschappell I'm still concerned about this issue affecting user on older devices. I'm not sure what versions of android and browser is being used so we need to keep an eye out and query users about their device info, when possible.

I notice in the server logs that when a user's socket reconnects to the server (meaning it was disconnected & not receiving messages) it does not reload the `/dashboard` endpoint, which seems to me it's not reloading the page.

### How to test
2 users will be logged in, lock the screen on the mobile user's device. After 5 minutes, send the mobile user a message from the other user. Unlock the screen on the mobile device and see if there is an icon showing new Mail on the mobile device. _Test this in different increments, 2min, 5min, 10min_.

**Comment by crobinson42** [comment]
@crobinson42 This issue/concern will be non-existent when the feature for socket disconnect/reconnect re-init the front-end store is implemented. Also planned with the user session timeout feature.
