### ISSUE TITLE
Location tabs load slowly

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#25]
There is a noticeable delay when navigating between tabs in a location when viewing its information area. I've seen this in both Chrome and Edge in the Sandbox server. The Service & Duties section's services and duties also expand very slowly in Edge, which may be related.

This has not yet been tested in the production server due to other issues preventing me from logging in, so I'm not sure if this is actually an optimization problem.

**Comment by jackschappell** [comment]
After watching my system's usage, I noticed that there was a significant increase in memory usage when trying to access locations and switch between their tabs. Chrome doesn't eat as much memory during these operations as Edge, but they are still visible.

In Edge, my system memory temporarily jumped from 2.2GB to 2.7GB before the tabs or locations loaded. In Chrome, it only when up to about 2.5GB. (Opening a link on this website in a new tab uses less memory, so something in the location sections may be very memory-intensive during the loading process).

**Comment by crobinson42** [comment]
Is this on sandbox or prod?

**Comment by crobinson42** [comment]
The sandbox server is **non-optimized code** which allows debugging in the console and showing clear stack traces if an error occurs. This will cause the UI/UX to be VERY slow as you continue to navigate the app on **Sandbox** server.

**Comment by crobinson42** [comment]
If you experience this in prod, please reopen.

**Comment by crobinson42** [comment]
This is being experienced in prod due to not using `export NODE_ENV=production` when starting prod server instances

**Comment by crobinson42** [comment]
FIXED with asset rebuild in production env mode.
