### ISSUE TITLE
Text in Text-Box Overflow

### ISSUE THREAD

**Issue by RonaldRob** [crobinson42/therms-public#28]
When writing a report entry, the text flows in the box as it should and is cut off by the limitations of the box and flows to the next line. When you hit save and review the report entry, the text is flowing out of the box and continues to the end of the pages "window limits" . It is starting in the correct position on the left side of the text box but it appears to be trying to fill the entire windows  space limitations to the right and not following the right alignment cut off of the text box.

**Comment by crobinson42** [comment]
@jackschappell please verify this behavior.

**Comment by crobinson42** [comment]
https://www.dropbox.com/s/adbxmrdza0haolw/Screenshot%202016-04-25%2021.34.48.png?dl=0

**Comment by jackschappell** [comment]
I can confirm this. It is happening in the mobile version of Google Chrome too.

**Comment by crobinson42** [comment]
Email word-wrap is breaking word mid-word: https://www.dropbox.com/s/as2nswjpbe79ytr/Screenshot%202016-04-26%2009.06.42.png?dl=0

**Comment by jackschappell** [comment]
Roger. @billpreston said it was disappearing off the edge of the page for him still, just like on THERMS. I'm not sure if that was a miscommunication or not.

**Comment by crobinson42** [comment]
Disregard the email word-wrap comment, this is a bug in OSX Mail previewer and how it renders html messages.
