### ISSUE TITLE
Duplicate Reports

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#3]
https://www.dropbox.com/s/33iaod11q4g7it1/Screenshot%202016-03-16%2015.03.37.png?dl=0

Both have the same database id.

**Comment by jackschappell** [comment]
I'm not able to recreate this bug on the sandbox server. Has this been fixed?

**Comment by crobinson42** [comment]
I'm unsure if it's fixed, I didn't change any code. My first thought was that it was a result of a double click on 'create report' but then I noticed in the url both reports had the same reportId which means it's probably an issue with the 'search reports' query.

Can you also create a test company on prod server and try to recreate?

**Comment by jackschappell** [comment]
I'm a little confused by what is happening. On the sandbox, it works as intended. On the production server [using the test company], I'm not getting any reports coming up at all.

**Comment by crobinson42** [comment]
prod and sandbox use different databases, did you create a report and it's not showing up on prod env?

**Comment by jackschappell** [comment]
Yeah. I just compared the consoles too. The sandbox shows the THERMS connection text, however the production shows "ErrorShelter sent 2 errors" instead. Not sure if that is related in any way or not, but those are the only differences I am seeing.

**Comment by crobinson42** [comment]
ok, i'll debug real quick and update on the issue.

**Comment by jackschappell** [comment]
Roger. The reports still exist by URL, so it appears to be saving them properly on that end.

**Comment by crobinson42** [comment]
The issue was due to a backend database query that sent back a response with 2 reports. It would only do this when there were more than 1 entry in a report by the same author. 

It's fixed and will be pushed to sbx and prod this afternoon. @jackschappell please verify anytime after 1700hr today and close.
