### ISSUE TITLE
Report Location Duties word-wrap formatting

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#30]
In a report that is showing location duties, when you click on 'details' the white-space formatting isn't in effect and needs to be added.

**Comment by jackschappell** [comment]
I'm not able to confirm this. Do you have more details? The formatting appears correct for me, unless I am missing it.

**Comment by crobinson42** [comment]
The email word-wrap breaks the word in the middle: https://www.dropbox.com/s/as2nswjpbe79ytr/Screenshot%202016-04-26%2009.06.42.png?dl=0

**Comment by crobinson42** [comment]
This appears while building a report that has Service Duties that have line breaks, ie: paragpraph spacing, by the user's input when inputing the Duty originally.
