### ISSUE TITLE
Page title inconsistency

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#32]
When viewing the THERMS homepage, the page title in the browser's title bar is in all capital letters, (just like in the previous version). After logging in and viewing the dashboard or other pages, however, it is stylized in such a way that only the first letter is capitalized, and all of the other ones are lowercase.

For visual purposes, shouldn't this be consistent? This could also confuse new users down the road when they try to properly refer to the name, (meaning marketing/branding issues).

**Comment by crobinson42** [comment]
Nice catch! Fixed.
