### ISSUE TITLE
Email System

### ISSUE THREAD

**Issue by billpreston** [crobinson42/therms-public#33]
Email system only has "Reply" "Mark as Unread" and "Delete"  There is no "Sent" feature to see any replies or what you sent.  There is also no filing system to store emails in so everything stays in the Inbox.

**Comment by jackschappell** [comment]
This is a duplicate of issue #31

**Comment by billpreston** [comment]
My bad… I apologize…  I’m not having a very good morning this morning…

**Comment by jackschappell** [comment]
No worries, sir! It happens!
