### ISSUE TITLE
Dispatch service call action information doesn't always show

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#34]
After clearing a service call, the action information, (Action Taken By, Action Response Time), handled by the responding officers does not always appear in the Dispatch section's log for that call. It appears to display properly in the reports they are linked to. (This bug may need confirming).

**Comment by jackschappell** [comment]
@crobinson42 See the first three Legion call logs for an example. The first one displays the information, whereas the next two don't. According to the responding officer for the first two calls, he cleared them both the exact same way. (I have not been able to check with the second responding officer who cleared the third one, though).

**Comment by crobinson42** [comment]
I suspect this might have something to do with it? https://www.dropbox.com/s/99mc1nc1080hjrx/Screenshot%202016-04-26%2015.45.33.png?dl=0
And a user forgetting to check the box.

**Comment by crobinson42** [comment]
@jackschappell Is this an issue? If it's not validated I think we should close this.

**Comment by jackschappell** [comment]
I'll close it for now. It may have been the Dispatchers screwing up. I haven't seen it happen since then. Worst case, we can always reopen it again later.
