### ISSUE TITLE
Can't send to multiple recipients/mass-message

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#35]
In the new version of THERMS, there is no option to send messages to multiple recipients, whether company-wide, or by individually selecting several users. This was a feature of the old version, and appeared to be very useful to many users managing their company.

(I couldn't find any planned feature cards for this. If it was dropped, please feel free to close this)

**Comment by crobinson42** [comment]
@jackschappell can you consolidate all the Mail section feature/enhancements to a single issue and use the 'checkbox' feature when opening it?

**Comment by crobinson42** [comment]
#31

**Comment by jackschappell** [comment]
Done!

See issue #36
