### ISSUE TITLE
Chronological Order in Reports

### ISSUE THREAD

**Issue by billpreston** [crobinson42/therms-public#38]
When reviewing the reports it appears that the entries are not going into the report in chronological order.  For instance... Zach Crain's Quest HQ report for last night goes 05:00, 12:00, 01:00 etc.  Not sure why it would do that.

**Comment by crobinson42** [comment]
@billpreston What browser are you using when you experienced this?

**Comment by billpreston** [comment]
Chrome

**Comment by jackschappell** [comment]
I'm not able to confirm this. Is this still happening to you @billpreston?

**Comment by crobinson42** [comment]
I don’t think he had enough coffee this morning….hahaha

**Comment by billpreston** [comment]
Could be….  But Will, Farnsey and Zach were all having the same issue so I guess I need to replace the Heroin flavored coffee with French Roast!

**Comment by jackschappell** [comment]
You could always try some of those Monster energy drinks you gave me! ;) 

Was this happening just on Zach's report, or was it happening on all of them? it sounds like the server may have forgotten the difference between AM and PM.

**Comment by jackschappell** [comment]
I just witnessed this on a report I was in the process of looking at to approve. Upon refreshing the page, the order was fixed.

**Comment by crobinson42** [comment]
fix pushed to sbx

**Comment by jackschappell** [comment]
This bug was random, but after extensive testing it appears to be fixed. You can go ahead and push it to the production server.

If it reappears, feel free to reopen.

**Comment by jackschappell** [comment]
This appears to have returned, however I have not yet found a way to reproduce it consistently. It shows up every so often, and a simple refresh of the page fixes it. It appears to be completely random at this time.

**Comment by crobinson42** [comment]
This is related to #27 having to do with a sort query syntax needing to be updated in our API. Fix is pushed to sbx.

**Comment by crobinson42** [comment]
The special duties fall in a slightly unordered, order:
https://www.dropbox.com/s/h1ge5s2rhcjyfbl/Screenshot%202016-05-19%2009.46.31.png?dl=0

**Comment by jackschappell** [comment]
This seems to be fixed for Chrome on Android and Windows.
