### ISSUE TITLE
Cannot create user in admin > add user

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#4]
Backend sends 400 - required attr missing `regions`

**Comment by jackschappell** [comment]
I'm able to confirm this on both servers.

**Comment by crobinson42** [comment]
Pushed code changes - please verify the fix and close the issue :+1:

**Comment by jackschappell** [comment]
I'm not seeing any changes on either server, even after a cache clearing, hard refresh, and relogging on the accounts.

**Comment by crobinson42** [comment]
are you sure? I just created an account under Legion Security's admin > add user. The new user email should go to `jack@therms.io`

**Comment by jackschappell** [comment]
My apologies, I am confusing issue reports! This is definitely fixed!
