### ISSUE TITLE
After 'Approve Report' show button 'go to next Report'

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#42]
When completing Report Approvals, after clicking on the 'Approve Report' button and report approval has been completed (finished loading), show a button 'Go to next Report' which will take the Admin user to the next pending-approval Report. This makes for easier Admin/Manager Approval processing time by reducing the clicks needed to approve reports.

**Comment by crobinson42** [comment]
This has been pushed to sbx, 12:30hr 1MAY16.

Create 3 Reports > Save Locations > Mark as Complete > Click Report Sidebar btn > Click on any pending approval report > Click approve 

The link 'view all' and btn 'next report ->'  should be visible and working.

**Comment by jackschappell** [comment]
This is working on the Sandbox. It can be pushed to production.
