### ISSUE TITLE
Dispatch Entry body text formatting

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#43]
Add appropriate user input preservation formatting to Report Entry body text components.

**Comment by crobinson42** [comment]
fix pushed to sbx.

**Comment by jackschappell** [comment]
Do you have a description of what was changed? I'm not sure what the original bug was or what to be looking for.

**Comment by crobinson42** [comment]
If the user, while entering in a dispatch txt body, input paragraph spacing, those spacings or line breaks are preserved when viewing the dispatch after it’s been saved.

**Comment by jackschappell** [comment]
This is fixed on the Sandbox. You can deploy it to the production server!
