### ISSUE TITLE
Build Report Location [service] Duties container does not update on socket msgs

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#44]
To recreate, start a new report, select a location that has service duties and save, expand a duty view and click complete and save, then delete the report entry it creates.

Experienced behavior: the complete duty summary line doesn't disappear after it's been deleted from the report entries.

Expected behavior: the Duties container should update with the Report Entries (create/update/destroy) that exist in the report log container

**Comment by crobinson42** [comment]
fix pushed to sbx

**Comment by jackschappell** [comment]
Working on Sandbox. This can be pushed to production.
