### ISSUE TITLE
Button to view all In-Progress reports

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#47]
In the old version of THERMS you could  click the top right button and hit ‘In-Progress’ and it would show all in-progress reports

**Comment by crobinson42** [comment]
@jackschappell What's your opinion on this? Currently this ability is easily accomplished by clicking **Reports** > **Search **. 

If we were to add this request in as a feature, where would the button go?

**Comment by jackschappell** [comment]
You could add a status section to the existing search method boxes. Currently there isn't a way to actually search based on any status type. It could simply be a dropdown box beside the others with your status options.

**Comment by crobinson42** [comment]
The sort order of search always orders a report that is in-progress first.

**Comment by crobinson42** [comment]
Add a link to the nav list on Reports module with a count next to it of how many are "In-progress" (only if there are in-progress reports).

https://www.dropbox.com/s/jbjs5cff1sxs100/Screenshot%202016-05-11%2018.50.42.png?dl=0

**Comment by crobinson42** [comment]
this feature was added.
