### ISSUE TITLE
"'Object.observe' is deprecated" warning in Google Chrome

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#5]
Not necessarily a bug, however as per the console in Google Chrome: "'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details."

For consistency and proper website validation, this may be worth looking into in the near future.

**Comment by crobinson42** [comment]
Ahh.. I haven't seen that one, yet. Is there any other information like a stack trace? I think the only place we use `Object.observe` is in our js-data models.

**Comment by jackschappell** [comment]
All it would give me is the reference on line 29269 of bundle.js.
(The containing function starts on line 29254)

`	  // Detect and do basic sanity checking on Object/Array.observe.
	  function detectObjectObserve() {
	    if (typeof Object.observe !== 'function' ||
	        typeof Array.observe !== 'function') {
	      return false;
	    }
	
	    var records = [];
	
	    function callback(recs) {
	      records = recs;
	    }
	
	    var test = {};
	    var arr = [];
	    Object.observe(test, callback);
	    Array.observe(arr, callback);
	    test.id = 1;
	    test.id = 2;
	    delete test.id;
	    arr.push(1, 2);
	    arr.length = 0;
	
	    Object.deliverChangeRecords(callback);
	    if (records.length !== 5)
	      return false;
	
	    if (records[0].type != 'add' ||
	        records[1].type != 'update' ||
	        records[2].type != 'delete' ||
	        records[3].type != 'splice' ||
	        records[4].type != 'splice') {
	      return false;
	    }
	
	    Object.unobserve(test, callback);
	    Array.unobserve(arr, callback);
	
	    return true;
	  }`

**Comment by crobinson42** [comment]
The functionality of the app will not be affected by this deprecation - our dependency on js-data.io uses a polyfill and when we upgrade to v3 `object` observation is handled fundamentally different.

There shouldn't be any other uses of `object.observe` in our app.
