### ISSUE TITLE
Report entry activity types don't always stay in order entered

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#50]
The activity types listed in report entries don't always stay in the order from which they were typed in after the entry is submitted. This is not a consistent issue, and appears to happen randomly.

(This is mainly a visual bug).

**Comment by crobinson42** [comment]
Is this a dup of #38?

**Comment by jackschappell** [comment]
Negative. #38 refers to report entries themselves being out of order based on time. This report refers to activity types in the report entries being out of order based on how they were entered.

**Comment by crobinson42** [comment]
Ah, OK. There currently is no expectaion of order. Do you suggest this as a
feature, to order the Activity Type categories in alphabetical order?
Ordering by input order would be tedious and unnecessary, IMO.

**Comment by jackschappell** [comment]
That should work fine.

**Comment by crobinson42** [comment]
Then at least they'd always be in the same order so there's consistency
across the app.

**Comment by crobinson42** [comment]
@jackschappell please check that this isn't already implemented.. I just went to add this and it appears I've already coded it to always show in alphabetical order.
```
let sortedActivityTypes = this.state.activityTypes.sort(function (a,b) {
        // sort by name
        return a.name < b.name ? -1 : 1;
      });
```

**Comment by jackschappell** [comment]
I checked to make sure before I created the bug report. It doesn't display them in alphabetical order.

**Comment by jackschappell** [comment]
Since the recent round of fixes pushed to the Sandbox and production servers, I haven't seen the bug with them displaying in random, non-alphabetical order return. I'll close this for now. Hopefully this is fixed for good.
