### ISSUE TITLE
Report Entry Sort Order [user preference]

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#52]
Have a button to change the sort order of the report entries when building a Report. This feature will toggle the sort order from `oldest`->`newest` and vica-versa

**Comment by crobinson42** [comment]
@jackschappell input/ideas on this?

**Comment by jackschappell** [comment]
I think that is a great idea as long as newest is the default, (similar to the old version of THERMS and how reports were ordered initially). That way users can quickly access their recent reports, but they can still sort them as needed if they are looking for an older one for referencing.

Your idea would definitely make searches easier too.

**Comment by crobinson42** [comment]
This has been added.
