### ISSUE TITLE
Ask users if they are sure they want to cancel on new, unsaved entries with data

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#53]
"If a new, unsaved entry contains text, ask the user if they are sure that they want to cancel when hitting the cancel button. That will save a lot of headaches for when users accidentally slip and hit cancel when they mean to hit save!
It could probably use the same code you already use for the delete buttons across THERMS."

**Comment by crobinson42** [comment]
This feature has been added.
