### ISSUE TITLE
Bulletin Board - Not all bulletins or replies show

### ISSUE THREAD

**Issue by jackschappell** [crobinson42/therms-public#58]
I'm assuming these two are probably linked.

1. When viewing the Bulletin Board, not all bulletins will show. Clicking the link to the Bulletin Board repeatedly will *sometimes* rectify the issue, however clicking it again causes the issue to reappear. This is not consistent.

2. When viewing a bulletin, not all users can see the comments. This issue is also not consistent.

**Comment by jackschappell** [comment]
Not sure if it is related, but on the Sandbox server with a company that has no bulletins, it appears to being trying to load them, but never finishes.

"Checking for Bulletins..."

**Comment by crobinson42** [comment]
> Not sure if it is related, but on the Sandbox server with a company that has no bulletins, it appears to being trying to load them, but never finishes.
"Checking for Bulletins..."

Does this happen every time or just sometimes?

> When viewing the Bulletin Board, not all bulletins will show. Clicking the link to the Bulletin Board repeatedly will sometimes rectify the issue, however clicking it again causes the issue to reappear. This is not consistent.

What do you mean by "not all"? Does a different order of random bulletins render, sometimes? 
When clicking the Bulletin Board sidebar button the issue reappears as in bulletins will go away?

> When viewing a bulletin, not all users can see the comments. This issue is also not consistent.

This probably is related to the parent Bulletin's issue, whatever it may be.

**Comment by jackschappell** [comment]
The order is fine. The newest bulletin remains at the top of the page, however all other bulletins seem to come and go. (A majority of the time, they just don't show at all unless you spam-click the Bulletin Board link). Some bulletins are also not visible at all.

The loading issue mentioned on the sandbox server also seems to be a permanent problem. It never loads anything, (although no bulletins have been created, so it shouldn't be trying to load empty data forever anyway).

**Comment by jackschappell** [comment]
![bulletinreplybug](https://cloud.githubusercontent.com/assets/17881452/15373920/b02cad06-1cfc-11e6-8cbf-fa13f3e0fa39.PNG)

> This is what I meant by the bulletins having replies not showing
> 4 replies to that bulletin, (my own included), and only 1 shows
> That is also the only bulletin showing up for me in the bulletin section right now. There should be others.
> If I click the Bulletin Board link repeatedly, sometimes I can get your "First Bulletin" one to show up.

![bulletinbugissues_consoleoutput](https://cloud.githubusercontent.com/assets/17881452/15373943/ca282cf8-1cfc-11e6-82a2-5c74c5309999.PNG)
This is the console output. Both issues appear to be related.

**Comment by crobinson42** [comment]
@jackschappell I need steps to reproduce this. There isn't anything that stands out in the code that would cause suspicion of this issue you're experiencing. 

- Does a page refresh when you're missing bulletins fix it?
- Does this happen after going to the bulletin page in a specific order?
- Does this happen on a specific device or browser?
- Does this happen towards the end of your user login session and a re-login fixes the issue?

**Comment by jackschappell** [comment]
1. No.
2. No.
3. Chrome on Windows is affected. I'm not getting it on Chrome for Android. Firefox on Windows seems to be fine too.
4. The issue remains regardless of my login status. It is consistent every time. The bulletin that does appear is sometimes different. Only the first bulletin reply usually shows on the displayed bulletin, if any exist.

**Comment by crobinson42** [comment]
@jackschappell This should have been fixed with the release last week that contained the new report entry types (incidents). 

Please investigate, since you're the only user experiencing this issue.

**Comment by jackschappell** [comment]
This doesn't appear to be fixed for me. Both the bulletins and their replies are still affected.

**Comment by crobinson42** [comment]
fix should be in sbx - waiting to deploy after regression UI testing.

**Comment by jackschappell** [comment]
This was fixed in Sandbox and Production.
