### ISSUE TITLE
Forgot Password not working / hanging

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#6]
Steps to reproduce:
therms.io/login > click the drop down arrow > forgot password > input an email > click submit

Expected:
Load message 'being sent to your email' and redirect to /login page

**Comment by crobinson42** [comment]
fixed backend issue - will get code updates on next prod deploy.

**Comment by crobinson42** [comment]
fixed in this merge https://github.com/crobinson42/therms/commit/55f387cbfd1355f861f1f1d6aa40668709511b59

@jackschappell please verify is working and close.

**Comment by jackschappell** [comment]
Upon tests with existing and non-existing database emails, I received a blank error message on both servers. Shortly after, both servers went out of service with "502 - Bad Gateway" messages when I attempted to refresh the page or load it normally.

**Comment by crobinson42** [comment]
@jackschappell I opened issue #11 for the above mentions for enhancements. 

The basic functionality is now working on, I had a typo in the code! Anyways, please verify you're receiving the email with a temp password in prod env and close.

**Comment by jackschappell** [comment]
Email received! This appears to be fixed.
