### ISSUE TITLE
Report Pending Count Inaccurate

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#64]
> j_schappell [10:08 PM] 
Although sometimes I'll briefly see the "go to next pending approval report" thing pop up with a number of reports from other companies when approving a lone one, but ot goes away a moment later on its own
[10:09] 
Yes, iPhone has an issue with that
[10:09] 
Some older, generic Android phones do too

**Comment by crobinson42** [comment]
@jackschappell Are we still experiencing this as an issue?

**Comment by jackschappell** [comment]
This seems to be fixed so far.
