### ISSUE TITLE
Mobile menu opens when bringing focus back to browser 

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#67]
To replicate on Android chrome login and close phone screen for 10 min then open screen back up, the refresh layover will load the. The menu is open. When you click on the menu button it will close and open again.

**Comment by jackschappell** [comment]
I can comfirm this issue. It appears to happen when manually reloading the page at any point too, as well as opening THERMS in a new tab/window.

**Comment by crobinson42** [comment]
pushed fix to sbx & prod. @jackschappell
