### ISSUE TITLE
Post Orders unable to separate paragraphs

### ISSUE THREAD

**Issue by billpreston** [crobinson42/therms-public#7]
I’m in the process of inputting data into the new version.  One thing I found was when I attempted to put the Post Orders in it saves it as one giant entry and will not let me break it into separate paragraphs. (same thing for Responding LE & Tow companies).

**Comment by crobinson42** [comment]
### Notes:
Add formatting to text to separate paragraphs and lines in location service/duties views.

**Comment by crobinson42** [comment]
CSS style formatting added to Location > Service & Duties paragraphs. Will be pushed to sbx & prod this afternoon.
