### ISSUE TITLE
Contact/Phone entries

### ISSUE THREAD

**Issue by billpreston** [crobinson42/therms-public#8]
when putting contacts in it has only one space for phone numbers but often managers will give me multiple phone numbers (i.e., work & cell numbers) I’m getting around that by putting them both in the same entry so that’s not that big of an issue.

**Comment by crobinson42** [comment]
### Notes:
Add the ability to add multiple phone numbers for a [location] contact

**Comment by crobinson42** [comment]
Looking into adding this in the next release - around May 16.

@billpreston in the meantime, you can use the notes section for additional phone numbers for location contacts.
