### ISSUE TITLE
Report Entry - Vehicle: leaving quick patrol times open throws error

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#84]
If you go to edit an entry, leaving the quick patrols time entry open and clicking save throws an error.

**Comment by jackschappell** [comment]
This also happens if you modify any time and leave it as invalid, then click save. (I'm not sure if they are related or not).

**Comment by crobinson42** [comment]
Does it break the page and require a refresh?

**Comment by jackschappell** [comment]
Yes. It also prevents you from being able to save your entry, even if the time is corrected. The only way to resolve the problem, (as you asked about), was to refresh the page and start over from scratch.

**Comment by crobinson42** [comment]
fixed and deploying.
