### ISSUE TITLE
Special Duties

### ISSUE THREAD

**Issue by billpreston** [crobinson42/therms-public#9]
Unable to insert completion of Special Duties into report text.

**Comment by crobinson42** [comment]
### Notes:
- Add special duties to locations
- Add special duties notes for completion
- Add special duties schedule (from date - to date)
- Add settings per location to show special duties when completing a report
- Add special duty 'ReportEntry' type

**Comment by crobinson42** [comment]
@billpreston just finished up the code. I'll be pushing to the production server in a few minutes.

**Comment by crobinson42** [comment]
This feature has been implemented. @billpreston Please add the duties to your locations under **Service & Duties**
https://github.com/crobinson42/therms/pull/93
