### ISSUE TITLE
Disappearing File Upload Input Form

### ISSUE THREAD

**Issue by crobinson42** [crobinson42/therms-public#98]
@jackschappell @farnsword report the file form will sometimes disappear after they've selected a file and may disappear while it's in the middle of an upload.

This is related to `key` prop on components. Fix is being implemented

**Comment by jackschappell** [comment]
I've had this happen during a successful file upload too, however it is not consistent. The issue also exists in other scenarios where it causes the file upload process to cancel out completely.

**Comment by jackschappell** [comment]
This is related to bug #74.

**Comment by crobinson42** [comment]
Ahh! I knew there was an issue open already... haha
